#!/usr/bin/env ruby
# encoding: UTF-8

## ruby -e "$(curl -fsSL raw.github.com/maciejczyzewski/hyhyhy/master/install)"

###############################################################################
#                                       _           _           _             #
#  Project                             | |         | |         | |            #
#                                      | |__  _   _| |__  _   _| |__  _   _   #
#  Copyright (C) 2005 - 2015,          | '_ \| | | | '_ \| | | | '_ \| | | |  #
#  Maciej A. Czyzewski,                | | | | |_| | | | | |_| | | | | |_| |  #
#  <maciejanthonyczyzewski@gmail.com>  |_| |_|\__, |_| |_|\__, |_| |_|\__, |  #
#                                              __/ |       __/ |       __/ |  #
#                                             |___/       |___/       |___/   #
#                                                                             #
#  This software is licensed as described in the file LICENSE, which          #
#  you should have received as part of this distribution.                     #
#                                                                             #
###############################################################################

# This script installs to /usr/local only. To install elsewhere you can just
# untar https://github.com/maciejczyzewski/hyhyhy/tarball/master
# anywhere you like or change the value of HYHYHY_PREFIX.

HYHYHY_PREFIX = '/usr/local'
HYHYHY_REPO = 'https://github.com/maciejczyzewski/hyhyhy'
HYHYHY_BRANCH = 'feature'

# =============================================================================
# UTILITIES
# =============================================================================

# Module: Colors in console
module Color extend self
  def blue; bold 34; end
  def green; bold 32; end
  def white; bold 39; end
  def red; underline 31; end
  def reset; escape 0; end
  def bold n; escape "1;#{n}" end
  def underline n; escape "4;#{n}" end
  def escape n; "\033[#{n}m" if STDOUT.tty? end
end

# Module: Split version to number
module Version
  def <=>(other)
    split(".").map { |i| i.to_i } <=> other.split(".").map { |i| i.to_i }
  end
end

# Class: Improve shell arguments
class Array
  def shell_s
    cp = dup
    first = cp.shift
    cp.map{ |arg| arg.gsub " ", "\\ " }.unshift(first) * " "
  end
end

# Function: normal output (blue color)
#   ohai "My full name is Maciej Anthony Czyzewski!"
def ohai *args
  puts "#{Color.blue}==>#{Color.white} #{args.shell_s}#{Color.reset}"
end

# Function: warning output (underline + red color)
#   warn "#{Color.white}hyhyhy#{Color.reset} is not installed!"
def warn warning
  puts "#{Color.red}Warning#{Color.reset}: #{warning.chomp}"
end

# Function: bash output during process
#   bash "/usr/bin/mkdir", "hyhyhy"
def bash *args
  abort "Failed during: #{args.shell_s}" unless Kernel.system(*args)
end

# Function: run commands with permissions
#   sudo "/bin/chmod", "o-w", HYHYHY_PREFIX
def sudo *args
  ohai "/usr/bin/sudo", *args
  bash "/usr/bin/sudo", *args
end

# Function: asks the question
#   ask "Are you ready for that?"
def ask question
  if STDIN.tty?
    while true
      print "#{Color.white}==>#{Color.reset} #{question} [Y/n]: "
      case gets.strip
        when 'Y', 'y', 'j', 'J', 'yes'
          return true
        when /\A[nN]o?\Z/
          return false
      end
    end
  else
    # Do not ask, anything agrees.
    # This improves the tests. (Travis)
    return true
  end
end

# Function: cross-platform way of finding an executable in the $PATH.
#   which ruby  #=> /usr/bin/ruby
def which cmd
  exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
    exts.each { |ext|
      exe = File.join(path, "#{cmd}#{ext}")
      return exe if File.executable?(exe) && !File.directory?(exe)
    }
  end

  # Nothing, not installed
  return nil
end

# =============================================================================
# COMPATIBILITY
# =============================================================================

# Invalidate sudo timestamp before exiting
at_exit { Kernel.system "/usr/bin/sudo", "-k" }

# The block form of Dir.chdir fails later if Dir.CWD doesn't exist which I
# guess is fair enough. Also sudo prints a warning message for no good reason
Dir.chdir "/usr"

# Abort, if there is no ruby or gem
abort "Oh My God! Script needs ruby and gem to work properly." unless
      which 'ruby' or which 'gem'

# Abort, if there is no git and curl
abort "Oh My God! Script needs git or curl to download hyhyhy." unless
      which 'git' and which 'curl'

# Abort, if ruby version is to old (>= 1.9.3)
abort "Oh My God! Requires ruby version >= 1.9.3" if
      RUBY_VERSION.split('.')[0,3].join.to_i < 193

# Save paths
RUBY = which 'ruby'
GEM  = which 'gem'
GIT  = which 'git'
CURL = which 'curl'

p RUBY
p GEM
p GIT
p CURL

abort "BREAK LINE"

# =============================================================================
# INSTALLER
# =============================================================================

# Show ASCII
puts "#{Color.green} _           _           _
| |         | |         | |
| |__  _   _| |__  _   _| |__  _   _
| '_ \\| | | | '_ \\| | | | '_ \\| | | |
| | | | |_| | | | | |_| | | | | |_| |
|_| |_|\\__, |_| |_|\\__, |_| |_|\\__, |
        __/ |       __/ |       __/ |
       |___/       |___/       |___/ #{Color.reset}"
puts "  #{Color.underline 35}github.com/maciejczyzewski/hyhyhy#{Color.reset}"
puts ""

# Anticipates
ohai "This script will prepare:"

# Structure
puts "executable:        #{HYHYHY_PREFIX}/bin/hyhyhy"    # executable
puts "directory:         #{HYHYHY_PREFIX}/hyhyhy/..."    # files & cache

# Anticipates
ohai "This script will install:"

# Packages
puts "rubygems packages: commander, kramdown, listen"    # rubygems packages
puts "bower packages:    katex, metricsgraphics, prism"  # bower packages

# Ask
abort unless ask "Are you ready for that?"

# Improve permissions
sudo "/bin/chmod", "o-w", HYHYHY_PREFIX

# Create main directory
Dir.chdir HYHYHY_PREFIX do
  sudo "/bin/mkdir", '-p', 'bin'
  sudo "/bin/mkdir", '-p', 'hyhyhy'
end

# Download files from repository
Dir.chdir "#{HYHYHY_PREFIX}/lib/hyhyhy" do
  # Here comes the party
  ohai "Downloading and installing hyhyhy..."

  if GIT
    # We do it in four steps to avoid merge errors when reinstalling
    bash GIT, "init", "-q"

    # "git remote add" will fail if the remote is defined in the global config
    bash GIT, "config", "remote.origin.url", HYHYHY_REPO
    bash GIT, "config", "remote.origin.fetch",
              "+refs/heads/*:refs/remotes/origin/*"

    args = GIT, "fetch", "origin",
           "#{HYHYHY_BRANCH}:refs/remotes/origin/#{HYHYHY_BRANCH}", "-n"
    args << "--depth=1" if ARGV.include? "--fast"
    bash(*args)

    bash GIT, "reset", "--hard", "origin/#{HYHYHY_BRANCH}"
  else
    warn "#{Color.white}git#{Color.reset} is not installed! " \
         "Do not worry, trying with #{Color.white}curl#{Color.reset}..."

    # Pipefail to cause the exit status from curl to propogate if it fails...
    # We use -k for curl because Leopard has a bunch of bad SSL certificates
    curl_flags = "fsSL"
    curl_flags << "k" if darwin_version <= "10.5"

    # Continue using Curl
    bash "/bin/bash -o pipefail -c '/usr/bin/curl -#{curl_flags} " \
         "#{HYHYHY_REPO}/tarball/#{HYHYHY_BRANCH} | " \
         "/usr/bin/tar xz -m --strip 1'"
  end

  # All needed packages
  ohai "Installing third-party libraries..."

  # Install packages from rubygems
  bash GEM, "install", "commander" # CLI
  bash GEM, "install", "kramdown"  # Markdown
  bash GEM, "install", "listen"    # Watcher
end

# Copy executable script
Dir.chdir HYHYHY_PREFIX do
  sudo "/bin/cp", "-p", "lib/hyhyhy/bin/hyhyhy", "bin/hyhyhy"
  sudo "/bin/cp", "-p", "lib/hyhyhy/bin/markdown", "bin/markdown"

  # Repair problems with permissions
  sudo "/bin/chmod", "u+rwx", "bin/hyhyhy"
  sudo "/bin/chmod", "u+rwx", "lib/hyhyhy/src/console.rb"
end

p ENV['PATH']

# Ooopppss?!
warn "#{HYHYHY_PREFIX}/bin is not in your PATH." unless
     ENV['PATH'].split(':').include? "#{HYHYHY_PREFIX}/bin"

# Good news
ohai "Installation successful!"

# A little bit of culture...
puts "Run `hyhyhy help` to get started"
