#!/bin/sh

echo "installation"                                              # Installation
echo "------------------------------------------------------------------------"

./install travis

echo "running hyhyhy CLI"                                          # Basic test
echo "------------------------------------------------------------------------"

hyhyhy

echo "------------------------------------------------------------------------"
echo "\033[32m✓ all tests passing! \033[0m"